In [1]:
import numpy as np

In [3]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [12]:
c=np.random.randint(1,10,10)
c

array([6, 3, 9, 1, 1, 9, 3, 1, 6, 2])

In [27]:
###PASSWORD GENERATOR###
import random
Upper_case="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
Lower_case="abcdefghijklmnopqrstuvwxyz"
Num="1234567890"
symbols="!@#$%^&"

Use_for=Upper_case+Lower_case+Num+symbols
Password_length=6
password="".join(random.sample(Use_for,Password_length))
print("Your Password is "+ str(password))

Your Password is MJ@pRs
